using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Finbourne.SdkConfig;
using Finbourne.SdkConfig.TokenProvider;
using Lusid.Sdk.Client;

namespace Lusid.Sdk.Utilities
{
    /// <summary>
    /// Factory to provide instances of the autogenerated LusidApi
    /// </summary>
    public interface ILusidApiFactory
    {
        /// <summary>
        /// Return the specific autogenerated Api
        /// </summary>
        TApi Api<TApi>() where TApi : class, IApiAccessor;
    }

    /// <inheritdoc />
    public class LusidApiFactory : ILusidApiFactory
    {
        private Dictionary<Type, IApiAccessor> _apis;

        /// <summary>
        /// Create a new factory using the specified configuration
        /// </summary>
        public LusidApiFactory(ApiConfiguration apiConfiguration)
        {
            // LUSID specifics
            apiConfiguration.Scope = "openid client groups offline_access";

            // Create configuration
            var tokenProvider = new ClientCredentialsFlowTokenProvider(apiConfiguration);
            var configuration = new TokenProviderConfiguration(tokenProvider)
            {
                BasePath = apiConfiguration.ApiUrl.AbsoluteUri
            };
            
            configuration.AddDefaultHeader("X-LUSID-Application", apiConfiguration.ApplicationName);

            Init(configuration);
        }
                
        /// <summary>
        /// Create a new factory using the specified configuration
        /// </summary>
        public LusidApiFactory(Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException(nameof(configuration));
            
            Init(configuration);
        }

        private void Init(Configuration configuration)
        {   
            IEnumerable<Type> apis = Assembly.GetAssembly(typeof(ApiClient))
                .GetTypes()
                .Where(t => typeof(IApiAccessor).IsAssignableFrom(t) && t.IsClass);

            _apis = new Dictionary<Type, IApiAccessor>();
            foreach (var api in apis)
            {
                if (!(Activator.CreateInstance(api, configuration) is IApiAccessor impl))
                {
                    throw new Exception($"Unable to create type {api}");
                }

                var @interface = api.GetInterfaces()
                    .First(i => typeof(IApiAccessor).IsAssignableFrom(i));

                _apis[api] = impl;
                _apis[@interface] = impl;
            }
        }

        /// <inheritdoc />
        public TApi Api<TApi>() where TApi : class, IApiAccessor
        {
            _apis.TryGetValue(typeof(TApi), out var api);

            if (api == null)
            {
                throw new InvalidOperationException($"Unable to find api: {typeof(TApi)}");
            }
            return api as TApi;
        }
    }
}